# Generated by Django 2.1 on 2020-01-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('college', models.CharField(choices=[('Government College of Arts, Science and Commerce, Khandola, Marcela Goa', 'Government College of Arts, Science and Commerce, Khandola, Marcela Goa'), ('Government College of Arts, Science & Commerce, Sanquelim-Goa', 'Government College of Arts, Science & Commerce, Sanquelim-Goa'), ('Government College of Arts, Science & Commerce, Quepem-Goa', 'Government College of Arts, Science & Commerce, Quepem-Goa'), ('Sant Sohirobanath Ambiye Government College of Arts & Commerce, VIrnoda-Pernem, Goa.', 'Sant Sohirobanath Ambiye Government College of Arts & Commerce, VIrnoda-Pernem, Goa.'), ('Government College of Commerce & Economics, Borda-Margao, Goa', 'Government College of Commerce & Economics, Borda-Margao, Goa'), ('Goa College of Music, Kala Academys Complex, Campal, Panaji-Goa.', 'Goa College of Music, Kala Academys Complex, Campal, Panaji-Goa.'), ('Goa College of Home Science, Campal, Panaji, Goa', 'Goa College of Home Science, Campal, Panaji, Goa'), ('II. Non-Government Aided Colleges', 'II. Non-Government Aided Colleges'), ('Shree Mallikarjun College of Arts & Commerce, Canacona Goa', 'Shree Mallikarjun College of Arts & Commerce, Canacona Goa'), ('Nirmala Institute of Education, Altinho Panaji, Goa', 'Nirmala Institute of Education, Altinho Panaji, Goa'), ('Dhempe College of Arts & Science, Panaji, Goa.', 'Dhempe College of Arts & Science, Panaji, Goa.'), ('V.M. Salgaocar College of law, Miramar, Panaji Goa', 'V.M. Salgaocar College of law, Miramar, Panaji Goa'), ('S.S. Dempo College of Commerce & Economics, Altinho, Panaji, Goa', 'S.S. Dempo College of Commerce & Economics, Altinho, Panaji, Goa'), ('College of Commerce and Economics, Ponda Goa', 'College of Commerce and Economics, Ponda Goa'), ('Carmel College of Arts, Science & Commerce for Women, Nuvem Goa', 'Carmel College of Arts, Science & Commerce for Women, Nuvem Goa')], default='Government College of Arts, Science and Commerce, Khandola, Marcela Goa', max_length=200)),
                ('occupation', models.CharField(choices=[('home-maker', 'home-maker'), ('Entreprenuer', 'Entreprenuer'), ('Employed', 'Employed')], default='Employed', max_length=100)),
                ('field', models.CharField(choices=[('Engineering', 'Engineering'), ('Arts', 'Arts'), ('Science', 'Science'), ('Nursery', 'Nursery'), ('Doctor', 'Doctor')], default='Engineering', max_length=100)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('year', models.CharField(choices=[('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017')], max_length=10)),
                ('validity', models.BooleanField(default=False)),
                ('register_number', models.IntegerField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='colleges',
            fields=[
                ('college_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('college_name', models.CharField(max_length=200)),
            ],
        ),
    ]
